#cloud-config


mounts:
  - [
      "172.17.0.",
      "/datadrive",
      auto,
      "defaults,noexec,nofail",
    ]

package_upgrade: true
packages:
  - nfs-kernel-server

write_files:
  - path: /etc/exports
    content: |
      /datadrive  172.17.0.0/24(rw,async,no_subtree_check)
runcmd:
  - sudo chown -R nobody:nogroup /datadrive/
  - sudo chmod 777 /datadrive/
  - exportfs -ra
  - systemctl restart nfs-kernel-server

